# Generated by Django 4.2.2 on 2023-08-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='defSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_mode', models.CharField(max_length=10)),
                ('signal_type_cafe_1', models.CharField(max_length=12)),
                ('width_time_cafe_1', models.CharField(max_length=4)),
                ('width_time_coil_1', models.CharField(max_length=4)),
                ('opVoltage_ls_1', models.CharField(max_length=5)),
                ('signal_type_cafe_2', models.CharField(max_length=12)),
                ('width_time_cafe_2', models.CharField(max_length=4)),
                ('width_time_coil_2', models.CharField(max_length=4)),
                ('opVoltage_ls_2', models.CharField(max_length=5)),
            ],
        ),
    ]
