# Generated by Django 4.2.2 on 2023-08-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defsettings',
            old_name='pct_mode',
            new_name='pctMode',
        ),
        migrations.RenameField(
            model_name='defsettings',
            old_name='signal_type_cafe_1',
            new_name='signalType_1',
        ),
        migrations.RenameField(
            model_name='defsettings',
            old_name='signal_type_cafe_2',
            new_name='signalType_2',
        ),
        migrations.RenameField(
            model_name='defsettings',
            old_name='width_time_cafe_1',
            new_name='widthTime_1',
        ),
        migrations.RenameField(
            model_name='defsettings',
            old_name='width_time_cafe_2',
            new_name='widthTime_2',
        ),
        migrations.RenameField(
            model_name='defsettings',
            old_name='width_time_coil_1',
            new_name='widthTime_coil_1',
        ),
        migrations.RenameField(
            model_name='defsettings',
            old_name='width_time_coil_2',
            new_name='widthTime_coil_2',
        ),
    ]
