# Generated by Django 4.2.7 on 2024-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0002_rename_pct_mode_defsettings_pctmode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempDataCt_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.BinaryField()),
                ('current', models.BinaryField()),
                ('setPoint', models.BinaryField()),
                ('feedback', models.BinaryField()),
                ('relayO', models.BinaryField()),
                ('relayC', models.BinaryField()),
                ('timeStamp', models.BinaryField()),
            ],
        ),
    ]
