# Generated by Django 4.2.7 on 2024-08-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0003_tempdatact_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='cycleTestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dut', models.CharField(max_length=30)),
                ('actuatorRef', models.CharField(max_length=30)),
                ('load', models.BooleanField()),
                ('loadDetails', models.BinaryField()),
                ('testerName', models.CharField(max_length=30)),
                ('observations', models.CharField(max_length=30)),
                ('operationVoltage', models.CharField(max_length=30)),
                ('inputType', models.CharField(max_length=30)),
                ('signalType', models.CharField(max_length=30)),
                ('pulseTime', models.CharField(max_length=30)),
                ('highValue', models.IntegerField()),
                ('lowValue', models.IntegerField()),
                ('day', models.CharField(max_length=30)),
                ('month', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=30)),
                ('fullDate', models.CharField(max_length=30)),
                ('dateEnd', models.CharField(max_length=30)),
                ('plannedTimeTest', models.CharField(max_length=30)),
                ('finalTimeTest', models.CharField(max_length=30)),
                ('temp', models.BinaryField()),
                ('current', models.BinaryField()),
                ('setPoint', models.BinaryField()),
                ('feedBack', models.BinaryField()),
                ('relayO', models.BinaryField()),
                ('relayC', models.BinaryField()),
                ('timeStamp', models.BinaryField()),
                ('relaysCounter', models.BinaryField()),
                ('feedBackCounter', models.BinaryField()),
            ],
        ),
    ]
