# Generated by Django 4.2.7 on 2024-08-14 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0006_alter_users_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='fullName',
            field=models.CharField(max_length=50),
        ),
    ]
