# Generated by Django 4.2.7 on 2024-08-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0008_alter_users_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletestdata',
            name='bauds',
            field=models.IntegerField(default=19200),
        ),
        migrations.AddField(
            model_name='cycletestdata',
            name='node',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cycletestdata',
            name='operationMode',
            field=models.CharField(default='Digital', max_length=30),
        ),
    ]
