# Generated by Django 4.2.7 on 2024-08-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0009_cycletestdata_bauds_cycletestdata_node_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletestdata',
            name='dateStart',
            field=models.CharField(default='', max_length=30),
        ),
    ]
