# Generated by Django 4.2.7 on 2024-09-09 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0010_cycletestdata_datestart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletestdata',
            name='pause',
            field=models.BooleanField(default=False),
        ),
    ]
