# Generated by Django 4.2.7 on 2024-09-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0011_cycletestdata_pause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycletestdata',
            name='pause',
            field=models.BinaryField(),
        ),
    ]
