# Generated by Django 4.2.7 on 2024-09-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0012_alter_cycletestdata_pause'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempdatact_a',
            name='pauseStatus',
            field=models.BinaryField(default=b''),
        ),
    ]
