# Generated by Django 4.2.7 on 2024-09-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0014_alter_tempdatact_a_pausestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempdatact_a',
            name='pauseStatus',
            field=models.BinaryField(default=b''),
        ),
    ]
