# Generated by Django 4.2.7 on 2024-09-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0015_alter_tempdatact_a_pausestatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cycletestdata',
            name='pause',
        ),
        migrations.RemoveField(
            model_name='tempdatact_a',
            name='pauseStatus',
        ),
    ]
