# Generated by Django 4.2.7 on 2024-09-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0016_remove_cycletestdata_pause_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycletestdata',
            name='pause',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='tempdatact_a',
            name='pauseStatus',
            field=models.BinaryField(default=b''),
        ),
    ]
