# Generated by Django 4.2.7 on 2024-09-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycle_test', '0017_cycletestdata_pause_tempdatact_a_pausestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempDataCtv2_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('current', models.IntegerField()),
                ('setPoint', models.IntegerField()),
                ('feedback', models.IntegerField()),
                ('relayO', models.IntegerField()),
                ('relayC', models.IntegerField()),
                ('timeStamp', models.FloatField()),
                ('pauseStatus', models.BooleanField()),
            ],
        ),
    ]
