from django.db import models

# Create your models here.
class defSettings(models.Model):
    pctMode = models.CharField(max_length=10)
    signalType_1 = models.CharField(max_length=12)
    widthTime_1 = models.CharField(max_length=4)
    widthTime_coil_1 = models.CharField(max_length=4)
    opVoltage_ls_1 = models.CharField(max_length=5)
    signalType_2 = models.CharField(max_length=12)
    widthTime_2 = models.CharField(max_length=4)
    widthTime_coil_2 = models.CharField(max_length=4)
    opVoltage_ls_2 = models.CharField(max_length=5)

class tempDataCt_a(models.Model):
    temp = models.BinaryField()
    current = models.BinaryField()
    setPoint = models.BinaryField()
    feedback = models.BinaryField()
    relayO = models.BinaryField()
    relayC = models.BinaryField()
    timeStamp = models.BinaryField()

class cycleTestData(models.Model):
    dut = models.CharField()
    actuatorRef = models.CharField()
    load = models.BooleanField()
    loadDetails = models.BinaryField()
    testerName = models.CharField()
    observations = models.CharField()
    operationVoltage = models.CharField()
    inputType = models.CharField()
    signalType = models.CharField()
    pulseTime = models.CharField()
    highValue = models.IntegerField()
    lowValue = models.IntegerField()
    day = models.CharField()
    month = models.CharField()
    year = models.CharField()
    fullDate = models.CharField()
    dateEnd = models.CharField()
    plannedTimeTest = models.CharField()
    finalTimeTest = models.CharField()
    temp = models.BinaryField()
    current = models.BinaryField()
    setPoint = models.BinaryField()
    feedBack = models.BinaryField()
    relaysCounter = models.BinaryField()
    feedBackCounter = models.BinaryField()
